integration-test:
  extends:
    file: ../.common/docker-compose.yml
    service: sbt
  entrypoint: sbt coverage it:test
  environment:
    - SHORT_URL_SVC_HOST=load-balance-svc.urlable-dev.85f92b22.svc.dockerapp.io
    - SHORT_URL_SVC_PORT=80